apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-k8s-url-monitor.fullname" . }}
  labels:
    {{- include "python-k8s-url-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "python-k8s-url-monitor.name" . }}
    release: {{ .Release.Name }}